import { Datalist, Option } from "../../_elements/Elements";

export const countries = [
  "Afghanistan",
  "Albanien",
  "Algeriet",
  "Angola",
  "Antigua och Barbuda",
  "Argentina",
  "Australien",
  "Azerbajdzjan",
  "Österrike",
  "Östtimor",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belgien",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnien och Hercegovina",
  "Botswana",
  "Brasilien",
  "Brunei Darussalam",
  "Bulgarien",
  "Burkina Faso",
  "Burundi",
  "Centralafrikanska Republiken",
  "Chile",
  "Colombia",
  "Costa Rica",
  "Cypern",
  "Danmark",
  "Demokratiska Republiken Kongo",
  "Dominikanska Republiken",
  "Ecuador",
  "Egypten",
  "El Salvador",
  "Elfenbenskusten",
  "Estland",
  "Etiopien",
  "Färöarna",
  "Förenade Arabemiraten",
  "Filippinerna",
  "Finland",
  "Frankrike",
  "Gabon",
  "Georgien",
  "Ghana",
  "Gibraltar",
  "Grönland",
  "Grekland",
  "Grenada",
  "Guatemala",
  "Honduras",
  "Hong Kong",
  "Indien",
  "Indonesien",
  "Irak",
  "Iran",
  "Irland",
  "Island",
  "Israel",
  "Italien",
  "Jamaica",
  "Japan",
  "Jemen",
  "Jersey",
  "Jordanien",
  "Kambodja",
  "Kanada",
  "Kazakstan",
  "Kenya",
  "Kina",
  "Kiribati",
  "Kroatien",
  "Kuba",
  "Kuwait",
  "Laos",
  "Lettland",
  "Libanon",
  "Libyen",
  "Litauen",
  "Luxemburg",
  "Madagaskar",
  "Makedonien",
  "Malawi",
  "Malaysia",
  "Maldiverna",
  "Mali",
  "Malta",
  "Marocko",
  "Mauritius",
  "Mexiko",
  "Mocambique",
  "Monaco",
  "Mongoliet",
  "Myanmar",
  "Namibia",
  "Nederländerna",
  "Nederländska Antillerna",
  "Nepal",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norge",
  "Nya Zeeland",
  "Oman",
  "Pakistan",
  "Panama",
  "Paraguay",
  "Peru",
  "Polen",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Rumänien",
  "Rwanda",
  "Ryssland",
  "Saint Lucia",
  "Saint Vincent och Grenadinerna",
  "Samoa",
  "San Marino",
  "Sao Tome och Principe",
  "Saudiarabien",
  "Schweiz",
  "Senegal",
  "Serbien och Montenegro",
  "Seychellerna",
  "Sierra Leone",
  "Singapore",
  "Slovakien",
  "Slovenien",
  "Somalia",
  "Spanien",
  "Sri Lanka",
  "Sudan",
  "Surinam",
  "Sverige",
  "Swaziland",
  "Sydafrika",
  "Sydkorea",
  "Syrien",
  "Taiwan",
  "Tanzania",
  "Thailand",
  "Tjeckien",
  "Trinidad och Tobago",
  "Tunisien",
  "Turkiet",
  "Tyskland",
  "Uganda",
  "Ukraina",
  "Ungern",
  "Uruguay",
  "USA",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Vitryssland",
  "Zambia",
  "Zimbabwe",
];
